/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboards': RouteRecordInfo<'/dashboards', '/dashboards', Record<never, never>, Record<never, never>>,
    '/dashboards/dashboard-page': RouteRecordInfo<'/dashboards/dashboard-page', '/dashboards/dashboard-page', Record<never, never>, Record<never, never>>,
    '/dashboards/portal-one': RouteRecordInfo<'/dashboards/portal-one', '/dashboards/portal-one', Record<never, never>, Record<never, never>>,
    '/dashboards/todo-reminder': RouteRecordInfo<'/dashboards/todo-reminder', '/dashboards/todo-reminder', Record<never, never>, Record<never, never>>,
  }
}
